"""create tbl

Revision ID: c26cdc900a1c
Revises: 
Create Date: 2023-05-15 10:15:35.730943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c26cdc900a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('usermetadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('following', sa.UUID(), nullable=True),
    sa.Column('follower', sa.UUID(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['follower'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_post',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('img_filename', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('count_like', sa.Integer(), nullable=True),
    sa.Column('liked_by', sa.JSON(), nullable=True),
    sa.Column('comment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('message_receive', sa.UUID(), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_receive'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reels_post',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reel_file', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('count_like', sa.Integer(), nullable=True),
    sa.Column('liked_by', sa.JSON(), nullable=True),
    sa.Column('comment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('add_story', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('count_like', sa.Integer(), nullable=True),
    sa.Column('liked_by', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story')
    op.drop_table('reels_post')
    op.drop_table('message')
    op.drop_table('image_post')
    op.drop_table('follow')
    op.drop_table('usermetadata')
    op.drop_table('user')
    # ### end Alembic commands ###
